### ISSUE TITLE
io.h: No such file or directory

### ISSUE THREAD

**Issue by zhanxiangsi** [HYPJUDY/caffe-dnnh#1]
Hello, I am compiling the "convert_triplet_imageset.cpp", and the error is io.h: No such file or directory. Even though there is a "io.h" in "/usr/include/x86_64-linux-gnu/sys", it cannot solve my problem. When I copy the file to "/usr/include", the result just likes the result when I simply comment the "#include <io.h>", in "io.cpp". i.e.  "error: ‘_open’ was not declared in this scope","error: ‘_close’ was not declared in this scope" and so on. So what should I do to compile the file "convert_triplet_imageset.cpp"

**Comment by zhanxiangsi** [comment]
Thanks to the help of Yupan and Fuchen, my problem has been successfully solved, through modifying "io.cpp" like following, instead of adding "io.h".
void MutiCVMatToDatum(const cv::Mat& cv_img1, const cv::Mat& cv_img2, const cv::Mat& cv_img3, Datum* datum)
{
CHECK(cv_img1.depth() == CV_8U) << "Image data type must be unsigned byte";// original image
CHECK(cv_img2.depth() == CV_8U) << "Image data type must be unsigned byte";//similar image
CHECK(cv_img3.depth() == CV_8U) << "Image data type must be unsigned byte";//different image
datum->set_channels(3 * cv_img1.channels());
datum->set_height(cv_img1.rows);
datum->set_width(cv_img1.cols);
datum->clear_data();
datum->clear_float_data();
datum->set_encoded(false);
int datum_channels = datum->channels();
int datum_height = datum->height();
int datum_width = datum->width();
int datum_size = datum_channels * datum_height * datum_width;
std::string buffer(datum_size, ' ');
for (int h = 0; h < datum_height; ++h)
{
       const uchar*ptr1 = cv_img1.ptr<uchar>(h); //original image
       const uchar*ptr2 = cv_img2.ptr<uchar>(h);// similar image
       const uchar*ptr3 = cv_img3.ptr<uchar>(h);// different image
       int img_index1 = 0;
       int img_index2 = 0;
       int img_index3 = 0;
       for (int w = 0; w < datum_width; ++w)
       {
              for (int c = 0; c < datum_channels / 3; ++c)
              {
                     int datum_index1 = (c*datum_height + h)*datum_width + w;
                     int datum_index2 = ((3 + c)*datum_height + h)*datum_width + w;
                     int datum_index3 = ((6 + c)*datum_height + h)*datum_width + w;
                     buffer[datum_index1] = static_cast<char>(ptr1[img_index1++]);
                     buffer[datum_index2] = static_cast<char>(ptr2[img_index2++]);
                     buffer[datum_index3] = static_cast<char>(ptr3[img_index3++]);
 
              }
       }
}
datum->set_data(buffer);
}

**Comment by HYPJUDY** [comment]
I'm glad to hear it. Closing this. Please feel free to reopen it if you meet any further problem.
