### ISSUE TITLE
cifar_hash_dataset.7z downloading

### ISSUE THREAD

**Issue by flexoter** [HYPJUDY/caffe-dnnh#7]
Please, share this dataset on some more available sources like google drive or smth. I just cannot create an baidu account for downloading your dataset. I would much appreciate your help

**Comment by HYPJUDY** [comment]
Sure. Updated with this commit https://github.com/HYPJUDY/caffe-dnnh/commit/ffd6143bd2098740a801aa0c92faa8b03d284996.
